### ISSUE TITLE
Migrate away from pstore and don't create cache if no IEV term referenced

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/iev#8]
I'm keep getting these temporary files created, when the documents don't even use anything from IEV.

<img width="288" alt="screen shot 2019-03-08 at 11 45 26 am" src="https://user-images.githubusercontent.com/11865/54006292-ac69e900-4197-11e9-9222-fa6ec7eb27dc.png">

Could we:
1. Use something similar to the Relaton store to store XML rather than `pstore`.
2. Do not create IEV caches if there are no IEV references?

Thanks!

**Comment by opoudjis** [comment]
I am generating those files in metanorma-standoc, which calls iev. So once @andrew2net has migrated away from pstore, I will need to rename the files as I have done for relaton, and I will need to create them lazily.

**Comment by andrew2net** [comment]
@opoudjis it's migrated it from Pstore.

**Comment by opoudjis** [comment]
Renaming iev files to follow relaton cache conventions; if a local cache is named for relaton, its iev counterpart will be `_iev` suffixed to the same name. (If the local cache document attribute is given with no value, it will just be called iev.)

iev initialisation is now lazy: it will only be invoked the first time an IEV reference is found.
